In [1]:
import torch
import numpy as np

In [2]:
# Initializing a tensor directly
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# Creating a tensor from a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
# Creating new tensors with the same shape as existing tensors
x_ones = torch.ones_like(x_data) # torch.ones_like creates a tensor of ones with the same shape as x_data
print(f"Tensor of ones: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype = torch.float) # torch.rand_like creates a tensor of random floats 0-1 with the same shape as x_data; dtype overrides the datatype to create floats
print(f"Tensor of rands: \n {x_rand} \n")

Tensor of ones: 
 tensor([[1, 1],
        [1, 1]]) 

Tensor of rands: 
 tensor([[0.2015, 0.2758],
        [0.0945, 0.5539]]) 



In [8]:
# Automatically generating tensors of defined shape
shape = (2, 3,) # tuple defining tensor dimensions
rand = torch.rand(shape)
ones = torch.ones(shape)
zeros = torch.zeros(shape)

print(f"Random Tensor: \n {rand} \n")
print(f"Ones Tensor: \n {ones} \n")
print(f"Zeros Tensor: \n {zeros}")

Random Tensor: 
 tensor([[0.6811, 0.1842, 0.7742],
        [0.4435, 0.3751, 0.5581]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# Extracting tensor attributes
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}") # note the syntax to extract the shape attribute
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
# Intel Macs can't use their GPUs for PyTorch - set up Google Colab for this
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")